name: Linux Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v4

      - name: Update package index
        run: sudo apt-get update

      - name: Install dependencies
        run: sudo apt -y install cmake liballegro5-dev libenet-dev libmad0-dev libfluidsynth-dev fluidsynth

      - name: Install dependencies
        run: sudo apt -y install cmake liballegro5-dev libenet-dev libmad0-dev libfluidsynth-dev fluidsynth

      - name: Build
        run: ./scripts/build-linux.sh

      - name: Bundle libs
        run: ./scripts/bundle-libs-linux.sh

      - name: Test executable
        run: |
          cd dist
          ./dunedynasty | grep "data directory"

      - name: Zip dist folder
        run: |
          cd dist
          zip -r dist.zip .

      - name: Delete Old Artifacts
        uses: actions/github-script@v7
        id: artifact
        with:
          script: |
            const res = await github.rest.actions.listArtifactsForRepo({
                owner: context.repo.owner,
                repo: context.repo.repo,
            })

            res.data.artifacts
                .filter(({ name }) => name === 'linux-build')
                .forEach(({ id }) => {
                  github.rest.actions.deleteArtifact({
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                      artifact_id: id,
                  })
                })

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: dist/dist.zip
