name: macOS ARM Build
on: [push, pull_request]

jobs:
  build:
    runs-on: macos-13-arm64
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: brew install cmake allegro fluid-synth mad enet
      - name: Build
        run: ./scripts/build-macos.sh
