name: macOS ARM64 Build
on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: | 
          brew install cmake dylibbundler
          brew uninstall sox mad
          brew fetch --force --bottle-tag=arm64_monterey argtable sdl2 dumb libogg flac libpng freetype libvorbis ca-certificates openssl@3 opus opusfile physfs theora giflib jpeg-turbo xz lz4 zstd libtiff webp pcre2 gettext glib lame mpg123 libsndfile portaudio readline allegro fluid-synth mad enet
          brew install $(brew --cache --bottle-tag=arm64_monterey argtable sdl2 dumb libogg flac libpng freetype libvorbis ca-certificates openssl@3 opus opusfile physfs theora giflib jpeg-turbo xz lz4 zstd libtiff webp pcre2 gettext glib lame mpg123 libsndfile portaudio readline allegro fluid-synth mad enet)

      - name: Build
        run: ./scripts/build-macos-arm64.sh

      - name: Bundle libs
        run: ./scripts/bundle-libs-macos.sh

      - name: Delete Old Artifacts
        uses: actions/github-script@v6
        id: artifact
        with:
          script: |
            const res = await github.rest.actions.listArtifactsForRepo({
                owner: context.repo.owner,
                repo: context.repo.repo,
            })

            res.data.artifacts
                .filter(({ name }) => name === 'macos-arm64-build')
                .forEach(({ id }) => {
                  github.rest.actions.deleteArtifact({
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                      artifact_id: id,
                  })
                })
                
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: macos-arm64-build
          path: dist
