name: macOS Intel Build
on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: brew install cmake allegro fluid-synth mad enet dylibbundler

      - name: Build
        run: ./scripts/build-macos.sh

      - name: Bundle libs
        run: ./scripts/bundle-libs-macos.sh

      - name: Delete Old Artifacts
        uses: actions/github-script@v6
        id: artifact
        with:
          script: |
            const res = await github.rest.actions.listArtifactsForRepo({
                owner: context.repo.owner,
                repo: context.repo.repo,
            })

            res.data.artifacts
                .filter(({ name }) => name === 'macos-intel-build')
                .forEach(({ id }) => {
                  github.rest.actions.deleteArtifact({
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                      artifact_id: id,
                  })
                })
                
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: macos-intel-build
          path: dist
