name: Windows Build
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: mingw-w64-x86_64-cmake mingw-w64-x86_64-gcc mingw-w64-x86_64-gdb mingw-w64-x86_64-allegro mingw-w64-x86_64-enet mingw-w64-x86_64-fluidsynth mingw-w64-x86_64-libmad
      - name: CI-Build
        run: |
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Release .
          ninja
